language: rust
rust: stable
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose
notifications:
  email: false
  irc:
    channels:
      - "irc.fyrechat.net#vana-commits"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
